all: AcWing785 AcWing786 AcWing787 AcWing788.cpp AcWing789 AcWing790 AcWing791 AcWing792

AcWing785:AcWing785.cpp
	g++ -g -o AcWing785 AcWing785.cpp

AcWing786:AcWing786.cpp
	g++ -g -o AcWing786 AcWing786.cpp

AcWing787:AcWing787.cpp
	g++ -g -o AcWing787 AcWing787.cpp

AcWing788:AcWing788.cpp
	g++ -g -o AcWing788 AcWing788.cpp

AcWing789:AcWing789.cpp
	g++ -g -o AcWing789 AcWing789.cpp 

AcWing790:AcWing790.cpp
	g++ -g -o AcWing790 AcWing790.cpp

AcWing791:AcWing791.cpp
	g++ -g -o AcWing791 AcWing791.cpp -std=c++11 

AcWing792:AcWing792.cpp
	g++ -g -o AcWing792 AcWing792.cpp -std=c++11 

clean:
	rm AcWing785 AcWing786 AcWing787 AcWing788.cpp AcWing789 AcWing790 AcWing791 AcWing792